version: "3.9"

services:
  discord:
    image: python:3.9
    container_name: discord
    restart: always
    volumes:
      - ./src:/app
    working_dir: /app
    command: >
      sh -c "
        python3 -m pip install -r requirements.txt &&
        python3 main.py
      "
